server:
  port: 8083
spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/traindb
    username: root
    password: 190112
  redis:
    host: 192.168.205.3
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
