server:
  port: 8083
spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/traindb
    username: root
    password: 190112
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 192.168.205.3
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true

